#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
# FOR A PARTICULAR PURPOSE. THIS CODE AND INFORMATION ARE NOT SUPPORTED BY XEBIALABS.
#

from flyway.FlywayUtil import FlywayUtil

flyway = FlywayUtil.create_flyway_client(thisCi.serverUrl, thisCi.username, thisCi.password)
flyway.log_results(thisCi.infoMode)
