language: java
notifications:
  slack:
    secure: IjmW3NfGWps2D67pJgLVcvddBERhy5fcbBrBmdTNL8+ZwtA4HEBAZ2z+1yL/Xv2mgaA9vBSbYDpdfqKV34QHU1HZkUIGY1kid9iToY5itF4pxxd/mhbbY4LXpWYVbRXByeMisiT+mTkwAu6FVynKhI0v6SPCpcAPH7QkMmuVwTXwZ14ri5iw7ffvpREaStlQCG4Zw9RbkDgOfGk/VMqgn5UT/L3HKUswFIKffGw/9BnK/fHruzCZJvBGt6URSUhhG/HfyJveDi2CqqOWBbYgtsRR3ARZ50P7Atjl0aT78X9MzTYVGnCvykl7P+dueqfni2H73KsIslq531PIkcfB2FHets+Ed9/DQwFhH2zCmm79QR/LWsYY6YoSpiEg8kuJ2FfE1uC+z3UN/zTPsgU4mefnHQ+ncNcLI9xjtDDgewHw6vJfqNELRU03C1UIgwhi4kfGtgsl61iwjLYVH/7LnVducGIq5W+hRWhbFq3wwgqFPH8KTxGAfW00V+A35rxEhpwg3k7Jmreb2C8zioOXwOKA6qGft3lt8rolyiGE1iPRL340r4S9cA/PX0kk3LizH1TNIcmLIZOc0RjOWpYtzh2qeb3uqIWkFMEUESWfTkZd2IydSLPhpz4/vqYBcKdpsoGypWjtEx0a6XKQTD9z2tqZ5owkg3KEgYika33xP0c=
deploy:
  provider: releases
  api_key:
    secure: oRKPQS3XMkqMaCNdFYMj6g9exVJeXBlnHe4gooPV/H0KWGD4/zr8JqR4XrZBiJ7uswwE3lJXF/HJuJ6NumxaVvHOK7FECoX30GikA44DHELSTMaYKsUoKTFF1hYwyh7oUynlwDjdk2nIHR5cgjua0tX3xkRTh8xgh/EvS6GD7VL6Tav7QEkfisUM8SgXljmDMAVvYwz7AOlgb4IHo604kVephImaRBMbSQ3IClMGALGPmJytwhHoevIV+FWrG8ED5iPfUDy+ch9cWavqwFsGYFORybW5bhRh3zSS0+ufsdWA4/yaXG+D5UUh71sjDfbGtSc/oWp6gLN6tCdYDSLvYp8KNkUaI5g8ipTeTh65SIr21/Rb06+dJ3AXCuVPsobEx1NtY/1dwXg4zv0tEnHa0zlU3hGjb2qrQ6wVhDe0kUv1t3NL7o4C2k6NTf3e96bQYJQaayufGmrhFwsZb239TJsCEVBB77kb2weNOF1RVTfkIVmGEGkCh6hJBJ4n9tz6gCabxZpqjK+lMWD/eptfCUak5YWgevdFlCP0+sfF0Ulxn/3xQNetXUnBZm+v94+UbQiMPpqrdAs+ZCK01HMOz7fiwEZWSJKg4C9iseNHXI13rE0N4TBWuv0MEV9VHIxwFVoobFKpxZrz5ClJ/r1nMAYV7I56U+IhUN/ktBEZ3kg=
  file: build/distributions/xld-flyway-plugin-2.3.1.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-flyway-plugin
